### ISSUE TITLE
Snippets not been pasted

### ISSUE THREAD

**Issue by AllBacksBlack** [GaurangTandon/ProKeys#12]
**Browser name:** - CHROME
**OS name:** - WINDOWS 10 ENT and KUBUNTU 16.04
**Version:** 3.0.0.1
**Site**  forum.xda-developers.com (vBulletin)
**Description:** Right Mouse Button >> ProKeys >> select any Snippet is not pasted at all.

I had to "Perform bulk action" >> "Select All" >> "Move to Folder" >> "Snippets" >> "Move to Folder"

Then the snippet paste correctly.

If the tab is closed, the Move to Folder has to be repeated.

below, my full backup:

```
 {
   "blockedSites": [],
   "charsToAutoInsertUserList": [
     [
       "(",
       ")"
     ],
     [
       "{",
       "}"
     ],
     [
       "\"",
       "\""
     ],
     [
       "[",
       "]"
     ]
   ],
   "dataUpdateVariable": false,
   "dataVersion": 1,
   "hotKey": [
     "ctrlKey",
     32
   ],
   "language": "English",
   "snippets": [
     "Snippets",
     1465242888361,
     {
       "name": "Device-Visitor",
       "body": "Hello\n\nThanks for using XDA Assist.\n\nGiven your report, we could not determine the [B]Manufacturer & Model[/B] of your device in order to better approach your issue.\n\nI will have to ask you to create a new Thread where you could be as detailed as possible regarding your devices information and issue.\n\nNice regards and good luck.\n\n[B]THREAD CLOSED[/B]\n\n.",
       "timestamp": 1465248736124
     },
     {
       "name": "Device-XDA",
       "body": "Hi %user%\n\nThanks for using XDA Assist.\n\nCould you please state the [B]Manufacturer & Model[/B] of your device so we would better approach your issue guiding you to the appropriate experts?\n\nI will be waiting for your reply.\n\nNice regards.\n\n.",
       "timestamp": 1465248532902
     },
     {
       "name": "Duplicate-XDA",
       "body": "Hi %user%\n\nThank you for using XDA Assist\n\nWe were able to determine that you have already posted your issue [url=%url%]here[/url]. It would be convenient that you give some time for our experts to analyse and answer you.\n\nIf you feel that it's taking too much, you may *bump up* you original thread by reposting some aditional information regarding it and so.\n\nThankful for your understanding.\n\nNice regards and good luck.\n\n[B]THREAD CLOSED[/B]\n\n.",
       "timestamp": 1465249467051
     },
     {
       "name": "English-Visitor",
       "body": "Hello\n\nThank you for using XDA Assist\n\nAccording to [url=http://forum.xda-developers.com/announcement.php?f=3194]XDA rules[/url] (4) we are an English Only forum and, as so, I will have to ask you to re-post your question in that language.\n\nThankful for your understanding.\n\nNice regards.\n\n[B]THREAD CLOSED[/B]\n\n.",
       "timestamp": 1465247595961
     },
     {
       "name": "English-XDA",
       "body": "Hi %user%\n\nThank you for using XDA Assist\n\nAccording to [url=http://forum.xda-developers.com/announcement.php?f=3194]XDA rules[/url] (4) we are an English Only forum and, as so, I will have to ask you to re-post your question in that language [U]within 2 days[/U] in order to keep this assistance up.\n\nThankful for your understanding.\n\nNice regards.\n\n.",
       "timestamp": 1465248182651
     },
     {
       "name": "MOD-Move",
       "body": "Please, move this thread to the [%name%] forum\n\n%url%\n\nThank you.",
       "timestamp": 1465239309692
     },
     {
       "name": "MOD-Senior",
       "body": "Please, verify this thread as a Senior Member has posted at XDA Assist forum.\n\nThank you.",
       "timestamp": 1465248306577
     },
     {
       "name": "QaA-Visitor",
       "body": "Hello\n\nPlease use the below link to register a XDA Account first, prior to start posting and replying onto our forums.\n\n[URL=\"http://forum.xda-developers.com/register.php\"]Join the Experts[/URL]\n\nWhen you complete your registration, I invite you to post your request in the below forum as our team of experts there should be able to help you:\n\n[URL=\"http://forum.xda-developers.com/android/help\"]Android Q&A, Help & Troubleshooting[/URL]\n\nBest regards and good luck.\n\n.",
       "timestamp": 1465238968590
     },
     {
       "name": "QaA-XDA",
       "body": "Hi %user%\n\nThank you for using XDA Assist\n\nAs we do not have an specific forum dedicated to your device yet, our experts at the below forum should be able to help you. Please be welcome to ask in there.\n\n[URL=\"http://forum.xda-developers.com/android/help\"]Android Q&A, Help & Troubleshooting[/URL]\n\nNice regards and good luck.\n\n.\n",
       "timestamp": 1465238874300
     }
   ],
   "tabKey": false,
   "visited": true
 }
```

**Comment by AllBacksBlack** [comment]
I could determine the following situations:

I've moved my Snippets to a sub-folder. They kept not pasting.

If I click first on the right mouse menu option "No Snippet to Insert" and then try to paste it, it works.

Sometimes a new right menu option "Default Snippet ..." (or so) appears and then, only perform bulk action give them back and removes that occasional odd option.

**Comment by GaurangTandon** [comment]
Hello @AllBacksBlack,

Very sorry for the late reply. I did not get any email notification for this issue, which is why I could not reply quickly. As for your issue, I am immediately looking into it and will reply back in a day with more info.

Thank you for your patience!

**Comment by GaurangTandon** [comment]
Hello @AllBacksBlack, I've tried to replicate your issue but without success. Every time I make any changes to my snippet data, they are properly reflected in the context menu. I am actually working on a new update to ProKeys. I will release it within a week, hopefully, it will fix your issue,

As for fixing your issue now, the only solution I can think of is that you delete the existing snippets, use the "Import/Restore" button to import your snippets back, and check if the context menu works properly.

Thank you for your patience!

**Comment by GaurangTandon** [comment]
>  so I assume that somehow, the local data is not found corectly when I first start the browser.

Oh, yes. I see the bug. This should be easy to fix. I'll try as fast as my schedule allows to get the new release done.

Thank you both @ThomasMz and @AllBacksBlack. Your feedback is highly appreciated :)

**Comment by GaurangTandon** [comment]
The issue has been resolved. Thank you for your patience! The fix will be live in v3.1.0, scheduled for release this week :)

**Comment by GaurangTandon** [comment]
A single snippet is currently shown as a top-level item instead of being nested inside a ProKeys top-level folder.

**Comment by GaurangTandon** [comment]
The following  have been entirely tested with 100% ok results - 

1. ctx menu snippet executed using sync and local storage - chunked and non-chunked data
2. placeholders working after execution
3. execution after update/reload/install
