### ISSUE TITLE
.selectList UI decide color

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#123]
The current color scheme is albeit too blank:

![image](https://cloud.githubusercontent.com/assets/6308683/23005025/efc475ca-f41f-11e6-814a-cf10c52382f8.png)

or do we really **don't** need colors in this box?

**Comment by iWrote** [comment]
colours will look weird. unless you want to provide feedback for some user action, leave it unchanged

**Comment by GaurangTandon** [comment]
Aren't the current colors confusing for users? I **really doubt** if anyone uses the "Move-to-folder" facility we provide at all. Or do you have a altogether better UI in mind?

**Comment by iWrote** [comment]
Why do you feel it's confusing?

**Comment by GaurangTandon** [comment]
What would "grey" color signify in that list People are used to the transparent light blue color on macOS, windows for selecting folders.

**Comment by GaurangTandon** [comment]
This is the color scheme for Windows: for selected and hover:

![image](https://user-images.githubusercontent.com/6308683/43001435-dc386edc-8c42-11e8-972c-99302caeb24b.png)

The end result looks great:

![image](https://user-images.githubusercontent.com/6308683/43001558-4030eac2-8c43-11e8-8983-6225d1495338.png)

Hover: `rgb(229, 243, 255)`  
Selected: `rgb(204, 232, 255)`  
Hovering over a selected item does nothing.
