### ISSUE TITLE
Possibility of unlimited revisions, and being able to delete revisions

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#125]
Do we even need unlimited revisions?
I think setting the max limit to 50 is also even a bad idea because we only have 5MB worth of space in the localStorage. 20 max revisions is good enough for someone who realizes their mistake of editing/deleting important stuff.
And why would one want to delete revisions?

**Comment by iWrote** [comment]
The way it currently works is fine. Did you get a user request about this? Let's not fix something that isn't broken.

20 revisions is more than enough. Users have import/export too,

Unlimited revisions would clog memory.

What do you mean by deleting revisions?

**Comment by GaurangTandon** [comment]
> What do you mean by deleting revisions?

If some data revision is useless, then trash it and make space for more revisions.
Basically, the current delete is "auto-delete" the oldest version; this extra delete button allows user to delete any revision; i guess it's useless as well; you're right;

closes #125
