### ISSUE TITLE
Open "Why you're leaving us?" form on ProKeys uninstall

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#129]
We must know why the user's leaving us. So, that we may improve ourselves. (Refer private email discussion  (17 Feb 2017) for details)

**TODO:** use the [`chrome.runtime.setUninstallURL`](https://developer.chrome.com/extensions/runtime#method-setUninstallURL) method to link to the survey
@iWrote please collaborate on the google form that I've shared with you. Since it doesn't have comments, we may post issues with it over here.

Here's the link to the form - https://docs.google.com/forms/d/e/1FAIpQLSdDAd8a1Edf4eUXhM4E1GALziNk6j1QYjI6gUqGdAXdYrueaw/viewform

**Comment by GaurangTandon** [comment]
**Issue#1: ** clicking on some checkboxes, like: "It doesn't work in Google Docs" - should open a small box telling the users that "ProKeys has a humongous lot of other features, GDoc is too mighty an app to integrate with, and that ProKeys is the best of the best!" or something similar.

**Comment by GaurangTandon** [comment]
Code written _and commented_ in `background.js`. 

The issue's still open to finish off making the form proper AND uncomment the code before the update goes live :P

**Comment by GaurangTandon** [comment]
**Issue#2**: Another useful thing would be to add an optional box - "Notify me when the bugs' fixed" asking for the user's email.

**Comment by GaurangTandon** [comment]
@iWrote I have completed making the form, including section redirects and everything. Please make necessary grammar/UX changes.

**Comment by GaurangTandon** [comment]
**The problem occurred on installation of the main page version v3.1.0!!!!!** And it doesn't show any errors in the console either :(

**Comment by iWrote** [comment]
Well ,if we're mentioning Optional everywhere for not-so-clever users, 

based on past experiences with users of the same kind - 
1. "I hit some bugs" needs a rephrase, what's the simple way of saying  - bug ?

2. Shouldn't all bug reporting forms redirect to Chome Webstore, so that we have all the problems in one place?

3. [This ](https://docs.google.com/forms/d/1gf0HRH-7aAOTBi40_7SIiQk1qNVUl8EFK4aUGSA-wJ8/edit#responses) form is also accepting responses. Isn't this getting a bit too spread out ?

**Comment by GaurangTandon** [comment]
1. "I found a bug" sounds better?
2. In the form, we're holding their hand like a kid and guiding them through the process. On the Chrome page, they'll be left alone in the wild, and will most probably quit the page. They won't even know whether they're supposed to write a review or read other people's reviews. And since they're most probably in _rage mode_, they'll just leave one star rating with-no-text and leave.
3. That form is basically useless, except for anonymity-freaks. This form is for everyone who specifically **_uninstalls our app._**

**Comment by GaurangTandon** [comment]
Oh, and **do not edit forms directly.** [We can't rollback.](https://productforums.google.com/forum/#!topic/docs/zS4Y2S0CfmM) if we ever wish to.

**Comment by iWrote** [comment]
Oops, sorry. I'll make a copy next time.

**Comment by GaurangTandon** [comment]
@iWrote issue closable now?

**Comment by GaurangTandon** [comment]
@iWrote **Suggestion:** How about, under the "I found ProKeys confusing" section, we add one more radio button "I read the help page to clear my confusion" - Yes/No.

**Comment by GaurangTandon** [comment]
_Update (for reference):_ Removed the question "Did you get a "This folder is empty" message on first install?" since 80% of all responses - and the latest responses - have always been "NO", indicating that #128  is correctly fixed.

**Comment by GaurangTandon** [comment]
I've gone ahead and made the corresponding change [mentioned an year](https://github.com/GaurangTandon/ProKeys/issues/129#issuecomment-284605713) earlier.
