### ISSUE TITLE
Play sound on inserting snippet

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#133]
I think this addition is pretty useless, except for any user with any remote disability.

Who might actually need this feature at all @iWrote ?

**Comment by iWrote** [comment]
nobody, meaningless noise, close issue

seeing text magically morph is good, immediate feedback

**Comment by GaurangTandon** [comment]
But what about people with vision-impairment? Those who use screen-readers, how would _they_ get feedback? #92

**Comment by GaurangTandon** [comment]
Closing as sorry but we definitely don't have time to care about everyone at this time.
