### ISSUE TITLE
Create feature promo image for Opera

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#139]
and upload it here = https://addons.opera.com/developer/package/_private?_/?tab=promoting

**Required size is 300x188px.** @iWrote just select the best existing image and properly crop it. It'll take 2mins to do. Do it right now. No milestones.

**Comment by GaurangTandon** [comment]
@iWrote I have uploaded the latest files for Opera. We need to change those promo images quick!

**Comment by GaurangTandon** [comment]
@iWrote I have uploaded the latest files for Opera. We need a feature marquee image and related things

**Comment by iWrote** [comment]
![appsupopera300x188](https://cloud.githubusercontent.com/assets/18333895/23645042/2ca20452-0330-11e7-86a0-5e1d7e5d9253.png)

I chose this one because 300x188 is quite small and this one has the largest icons.

**Comment by GaurangTandon** [comment]
We need a marquee promo image, that tells the user what prokeys is,
not where it works.
It's displayed in the main Opera page.
Can't you resize the "Get more work done in every keystroke" image?

**Comment by iWrote** [comment]
I just wanted to mention that while resizing does take 4-5 minutes at max, 
cropping != resizing;
cropping  = badidea;
resize = changeFromSrcForMinimalLossInQuality;


![prok300x188](https://cloud.githubusercontent.com/assets/18333895/24198377/b018b32e-0f2b-11e7-933d-5c1ab2810cf6.png)

P.S. Never got a ping for this after the first time. So I never got round to doing it until today when I decided to procrastinate through minor tasks . . .

**Comment by GaurangTandon** [comment]
Successfully uploaded. Thanks!

**Comment by GaurangTandon** [comment]
PS: don't edit [your posts ](https://github.com/GaurangTandon/ProKeys/issues/139#issuecomment-284637207) some time later after you've posted them; i don't get pings for edits; so I don't read them either
