### ISSUE TITLE
Past Data Versions popup UI leak + suggestions

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#15]
![pdv_uileak](https://cloud.githubusercontent.com/assets/18333895/16447383/f48c1ad0-3e09-11e6-9e1b-d13a375a1c67.PNG)

**Comment by iWrote** [comment]
Pertains to v3.1 (Not live yet.)

**Comment by GaurangTandon** [comment]
fixed all except UI leak problem, that I am deferring to 3.3.0 (because it's not really urgent and mighty difficult to fix!)

**Comment by GaurangTandon** [comment]
Sorry, not really keen on fixing that leaking UI. Will require too many changes, and as it stands, it still works so... :P
