### ISSUE TITLE
"Unselect all" button should ALSO be shown in bulk action panel

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#155]
instead of the "Select all" button

**Comment by GaurangTandon** [comment]
I think both the buttons should be simultaneously shown; user can use whatever he likes

**Comment by iWrote** [comment]
In a lot of programs i just use the select all button twice to deselect all. I don't see the need for an extra button.

**Comment by GaurangTandon** [comment]
You're right, and this is precisely what I've implemented this time. Pressing it twice should unselect all :)
