### ISSUE TITLE
Add a clone button

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#157]
That is shown when user views snippet in unexpanded mode. Like this:

![screen](https://cloud.githubusercontent.com/assets/6308683/23823779/e591a74e-068f-11e7-8b22-467011e392e4.png)

Suggested icon: http://fontawesome.io/icon/clone/

Useful where you've similar snippets to be sent to boss, colleague, client, etc. with only minor changes.

**Comment by GaurangTandon** [comment]
**Implementation:**
1. Both folders and snippets can be cloned.
2. The cloned object is assigned a name `prevName_(count++)` with same body text, and is inserted _right after_ the current object in parent folder list.

**Comment by MartinN3** [comment]
Great feature, its really missing for regular eshop translations
