### ISSUE TITLE
 v3.1 - folder select list - empty folders should not have arrows

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#16]
Empty folders (that cannot be collapsed) should have the indent but **not the interactive arrow.**

![arrowglitch](https://cloud.githubusercontent.com/assets/18333895/16447676/464feed6-3e0b-11e6-90e7-e8fae312c689.PNG)

Pertaining to v3.1 (not live yet.)

**Comment by GaurangTandon** [comment]
That's tough to fix, but I will.

*Note: Issue pertains to v3.1.0*

**Comment by GaurangTandon** [comment]
fixed. thanks for reporting!
