### ISSUE TITLE
Urgent: Chrome Webstore Description edits

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#17]
> *NEW: Brand new ProKeys v3.0.0 - completely revamped every single thing - from the UI to the Features - everything has been repolished!*

to

> *NEW: ProKeys v3.0.0 - completely revamped the UI and refined the Features!*

because features can't be revamped and the revision is shorter.

**Comment by iWrote** [comment]
or 

> NEW: ProKeys v3.0.0 - Revamped UI and Refined Features!

but perhaps it's too short. I'd like the former one.

**Comment by GaurangTandon** [comment]
Fixed :)
