### ISSUE TITLE
[User Report] ProKeys inserts non-breaking spaces in unexpected way

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#171]
_Reported by Simon, Andrew through support email_

Example site: https://dict.leo.org/forum/index.php?lp=ende&lang=en.

As per report: on inserting brackets, ProKeys

> automatically makes all the spaces I've used into non-breaking spaces. As a result, my posts don't wrap properly - instead, the text carries on past the right edge of the text field.

**Dev note:** This can also be seen in Gmail - when inserting braces in the middle of a long parargaph, it suddenly changes the text wrap behavior, in case the paragraph is multiline and long enough.

**Workaround:**  disable the auto-insertion of parentheses and quotations in the settings.

**Comment by iWrote** [comment]
I've had that too! ProKeys does mess up text wrap. I just got used to it, hehe.
