### ISSUE TITLE
Sort snippets before folders in context menu snippet insertion

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#174]
_Reported on prokeys email by Quinn_

Prototype image courtesy thanks to Quinn!

![image](https://cloud.githubusercontent.com/assets/6308683/25383240/d632e7ce-29d8-11e7-8954-5db540dd0097.png)
![image](https://cloud.githubusercontent.com/assets/6308683/25383243/d91d7634-29d8-11e7-98b8-1e18b1faafcc.png)

Having snippets listed before folders would enable us to quickly reach them.

**Comment by GaurangTandon** [comment]
@iWrote Need your opinion on this. Won't people want to reach folders first maybe? Because they've got an hierarchical level of organization and rarely use top-level snippets?

**Comment by GaurangTandon** [comment]
Thoughts anyone?

**Comment by JAIDEV123** [comment]
@GaurangTandon Makes sense but there are gonna be ppl who benefit from either. Pro users with folder will prefer proposed but casual users will prefer first

**Comment by GaurangTandon** [comment]
Hmm, well right, so we close this issue right?

**Comment by JAIDEV123** [comment]
@GaurangTandon I think so. Adding it as an option would probably just confuse users due to the number of settings.

**Comment by JAIDEV123** [comment]
@JAIDEV123 On this note, I am wondering if a user ui survey must be put out.

**Comment by GaurangTandon** [comment]
yeah, we could. But let it accumulate in count. Once we have many such things to query, we may make a survey.
