### ISSUE TITLE
v3.1 FeatureBreaking Glitch in Snippet Editor

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#18]
(Pencil icon menu)
Pressing enter to add a line break in the snippets' expansion does something weird. Instead of taking the cursor to the next line, I think it pastes a whole new text field!

The glitch is easy to reproduce. Just press enter while editing a snips expansion. Press it multiple times  to see it more clearly.

(enter = return key)

**Comment by GaurangTandon** [comment]
I have been pressing my enter key like a semi-automatic machine gun, have refreshed the page twice, tried in both create new and edit snip panels, with no weird results :/

Are you sure you don't have another key press manipulating software?

**Comment by iWrote** [comment]
So should I close this one? The <div> <br> spam issue is the same thing right?

**Comment by GaurangTandon** [comment]
No, I haven't fixed it yet. Problem was in CSS selectors, spam issue's different.

**Comment by GaurangTandon** [comment]
fixed by adding ".body-editor" class to .body > div
