### ISSUE TITLE
Allow locking down ProKeys editor with a password

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#186]
Users might forget to logout of their Chrome browser in their workplace, hence, we need to secure their ProKeys editor from possible external manipulation of their snippets.

Imagine, if someone manipulates your snippets to convey meanings to recipients other than what was intended. Having become habitual to using the snippet and pressing Ctrl+Enter, you might not notice those changes. This can have disastrous effects on your business.

**Comment by GaurangTandon** [comment]
This has further complications than are implicitly visible. Locking down the editor is barely of any use when the enthusiastic hacker will open the DevTools and do what they wish to. Since the `Data` is stored as a public variable, and `chrome.storage.*` API is public too, the hacker will have no trouble in changing the `Data` from there.

Even if the `Data` was in a private variable, they can still call the `chrome.storage.*` API, as the data storage key is publicly visible in the code anyway.

I hence doubt if this is possible at all. If anyone has suggestions, drop a line and I'll reopen the issue.

**Comment by ammarbinfaisal** [comment]
What if the person trying to change the snippets doesn't know all this(changing the data from devtools)?<br/> I don't think that only coders use this extension.

**Comment by GaurangTandon** [comment]
Hi Ammar! :) you're right that only coders don't use this extension.
However, if I'm offering password protection, I have to make it foolproof
against all types of possibilities. This also includes the enthusiastic
hackers I was talking about.

**Comment by ammarbinfaisal** [comment]
I also though about it while commenting, and I am not much experienced to know how that can be done.

As far as I know the easiest and tge best way is to store data on a remote server in a db and charge users for that.

**Comment by GaurangTandon** [comment]
No, even that does not solve this problem :|

**Comment by ammarbinfaisal** [comment]
Okay, I understand it now.

**Comment by iWrote** [comment]
You could still give such users what they want: just call it Child Lock Password. 

The name will convey that this feature was never meant to protect snips against a malicious hacker. And it's enough to keep kids or not-so-savvy disgruntled colleagues at bay. 

A large part of the userbase is (probably) people who perform clerical tasks in workplaces where this barrier is adequate, practical security.

This won't solve the problems you state; this might fulfill this user's need without putting you in an irresponsible position. 

> Child Lock Password - _might also lock out immature adults_ ;)

**Comment by GaurangTandon** [comment]
I agree with your motivation. We can even find this in Windows, for example, you need to key in your admin password to uninstall/install programs, even if you're already logged in with that account. Also, most web services like Facebook confirm your old password before allowing you access to sensitive settings, even when you're logged in. 

However, I do not like the approach to security being mentioned in this issue very plausible. Think of a real world analogy: Would you put a sum of ₹5000 in a transparent glass locker, with everyone knowing it has that cash, in a public place? I know most passers-by would ignore the box, but the genuinely interested people will sneak their way in the night and break the glass and run away with the money anyway. Would you be able to have a sound sleep at night in such a case? I guess no.

Hence, not only this feature is a bit long on the implementation side of the thing, but also it does not seem to have a very compelling case for itself in easing user's lives. Sorry for the pessimistic view, but - as of writing - this is a No from my side.

Feel free to pursue me further though, with more input ^_^
