### ISSUE TITLE
v3.1 Add null as a delimiter.

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#19]
In the text below **(originally typed in gmail text area)-**
 
brb

Space is set as a delimiter in the default list. But the "brb" above didn't expand like the one below, probably because it is on the edge of the window so there is no character before it. No delimiter.
(The dot before expanded brb was added to show the space automatically removed by githubs formatting engine.)

 . be right back

Can you permanently add null to the list of delimiters or something? So that snips typed in the very edge of a window also expand.

**Comment by GaurangTandon** [comment]
Oh god how did I forget this edge case???? Thanks for noticing, am fixing.

**Comment by GaurangTandon** [comment]
My fix seems to work everywhere except the Help page! it is rather odd :/ I am still investigating...

**Comment by GaurangTandon** [comment]
Fixed. Thanks for reporting.

The mechanism now goes from shortest to longest snip but now does not immediately return on finding the shortest snippet. It undergoes 30 iterations (limit on snip name) until the longest one and then only it returns the last matched (=> longest) snip.

**Comment by GaurangTandon** [comment]
just a follow up, the new logic of expanding snippets is from longest to shortest (based on many many many customer requests)
