### ISSUE TITLE
Swapping between textarea and rich text editor codifies html entities

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#191]
Characters like `<` or `>` get converted into `&lt;` and `&gt;`.

**TODO:** resolve this issue. Make sure it also does not occur while executing the snippet in rich text areas or textboxes.

**Comment by GaurangTandon** [comment]
It should be noted that text like `&amp;` gets converted to `&` when swapping from textarea to rich text editor, which I don't think is an issue because that's the whole purpose of the swap: creating actual html out of html-like text.

**Comment by ammarbinfaisal** [comment]
>  which I don't think is an issue because that's the whole purpose of the swap: creating actual html out of html-like text.

But on changing back to textarea from rte the textarea should have the html and not the plain text. What if someone swapped to rte to just have the preview of html?
