### ISSUE TITLE
Clicking "About" disables ProKeys on Chrome 64-bit, Ubuntu 

### ISSUE THREAD

**Issue by erelsgl** [GaurangTandon/ProKeys#192]
### Data
**Browser name:** - Chrome Version 63.0.3239.84 (Official Build) (64-bit)
**OS name:** - Ubuntu 16.04
**Site** where ProKeys is functioning improperly -chrome-extension://ekfnbpgmmeahnnlpjibofkobpdkifapn/html/options.html#snippets

### **Description:** 
**Steps to reproduce issue**
Doing the following in latest ProKeys version will cause the problem I'm writing about.

1. Click the "About" button. 

**Actual behavior**
The above steps result in: "ProKeys" disappears from Chrome.
When I open Chrome "extensions", I see that it is "corrupted" and needs to be repaired.

**Expected behavior**
The following was supposed to happen/should have happened: 
See information about prokeys.

**Comment by GaurangTandon** [comment]
Sorry for the trouble you had to face! That is really strange. I wonder if it is an Ubuntu only issue. I don't own one OS, so please give me some time in fixing this. Thanks for your cooperation!

**Comment by ammarbinfaisal** [comment]
I just cloned the repo, loaded Prokeys unpacked and then clicked on the about button. That didnt disable prokeys. But it does happen with the prokeys added from the chrome store.

**My OS:** Ubuntu 16.04
**Chrome version:** 66.x

**Comment by GaurangTandon** [comment]
Hmm... That's odd :( can you please share any errors that you receive in
the browser console/dev tools (F12) ?

I'm guessing that I'm using a DOM property that is not present in Ubuntu.

**Comment by ammarbinfaisal** [comment]
> can you please share any errors that you receive in
the browser console/dev tools (F12) ?

There are two errors but they are not because of any non-existent  DOM property.
Only t.png and f.png are not available(GET request for them is failing).
And that is happening because you have named it t.PNG and f.PNG. Changing it to lower case fixes it.<br/> and to know why see [this](https://superuser.com/questions/881804/case-sensitive-file-extensions-in-windows-and-linux). _(I hope you'll understand it better than I did. :smile: )_

**Comment by GaurangTandon** [comment]
Wow, thanks for the help @ammarbinfaisal ! I'll merge the PR asap by tomorrow or day-after. I only need to ensure that the current task runner (gulp) doesn't mess up the file extensions case. (it automatically copies the files from one folder to another)

**Comment by ammarbinfaisal** [comment]
👍
