### ISSUE TITLE
Support indent/outdent in snippet editor

### ISSUE THREAD

**Issue by AHThomas** [GaurangTandon/ProKeys#195]
In the styled textbox editor, would be nice if it supported indent/outdent so we could indent several lines of text within our snippets

**Comment by GaurangTandon** [comment]
Thanks for your feedback! As of now, I can press the `[Tab]` key and it automatically inserts an indent. Pressing it twice gives two indents. Does it not work on your end?

**Comment by GaurangTandon** [comment]
Sorry, but I have to close this issue for lack of further participation. Please feel free to comment if you've any feedback.
