### ISSUE TITLE
Don't autocomplete for specific bracket patterns like :-(

### ISSUE THREAD

**Issue by orschiro** [GaurangTandon/ProKeys#197]
@GaurangTandon! :-)

Really love this powerful bracket autocomplete feature. 

However, it's not always useful, like when trying to make a smiley :-(

Can you check this video: https://www.useloom.com/share/4b973fb9e51c40a1b5e1c0f55debd3e8

and let me know your thoughts?

Thanks!

**Comment by GaurangTandon** [comment]
Hi, sorry for the delay! 

I understand your request, and truth be told it's something I've wanted to fix as well :P 

These are the emojis I'll be supporting currently: `:-(`, `:(`, `:-{`, `:{`. Let me know if you need more!

**Comment by orschiro** [comment]
Thanks, appreciated!
