### ISSUE TITLE
ProKeys snippet span element showing up in BBPress

### ISSUE THREAD

**Issue by Li-An** [GaurangTandon/ProKeys#198]
**Browser name:** - Chrome
**OS name:** - Win 10 64 bits
**Site** where ProKeys is functioning improperly - https://wpfr.net/support/ ) bbPress

 Insert text in message field with Prokeys

The automatically inserted text got `<span class="prokeys-snippet-text">`. This is observed not in the text editor but in the published post.

Is there a way to prevent this ?

**Comment by GaurangTandon** [comment]
Hello, sorry for the delay!

I tested the BBPress forum on the site you linked to, and ProKeys is working correctly for all the cases: inserting snippet with or without placeholders, through context menu or hotkeys, at the end of a paragraph, beginning, or in the middle.

Please confirm with the exact snippet text you used, so I may be to help you further. Thanks!

**Comment by Li-An** [comment]
I suppose you did not publish the test message. When inserting the snippet in edit mode, everything is OK but when published, the HTML is showing. It’s a problem relative to BBPress (it does not support pasting with coded text) and it seems that Prokeys does not insert raw text.

**Comment by GaurangTandon** [comment]
That `span` element is necessary for the functioning of ProKeys, because otherwise it's hard to keep track of where the text was inserted in a content editable node, like this one. The `span` element is also inserted in GMail, Outlook, Evernote and any other content editable you might find on any website.

I'll see what exemptions I can make for BBPress.

**Comment by Li-An** [comment]
I will ask.

**Comment by Li-An** [comment]
I installed BBPress on a test site and Prokey works as intended. So, it seems it’s not related to your plugin. Investigations are on the way.

**Comment by GaurangTandon** [comment]
Hi Li-An, it's almost a month since we last checked on this issue. Do you have any new updates on this?

**Comment by Li-An** [comment]
The team has given no answer for the moment. I suspect a plugin relative to BBPress that they installed. I will ask again in september.

**Comment by GaurangTandon** [comment]
Hi @Li-An, just following up on this to ask was there any update?
