### ISSUE TITLE
"Disabled" ProKeys icon on sites where it is blocked by the user

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#205]
Most extensions like Tampermonkey/Ghostery have icons in the extension tray (top right) which turn grey on sites where the user disables them. Could be a neat visual addition for ProKeys as well. Though @iWrote you'll need to decide the color for that. Could you please do that?

**Comment by iWrote** [comment]
Can you change the icon on the fly? If yes, then I'll send you some this weekend. Or are you somehow restricted to modifying the current icons shades? 

> you'll need to **decide the color for that**. Could you please do that?

I don't understand what you need me to do. Just make a new icon, same specs as before, right?

**Comment by GaurangTandon** [comment]
For example, here's Tampermonkey on a website where it is not currently functioning:

![image](https://user-images.githubusercontent.com/6308683/43003766-37ccb14c-8c4b-11e8-8ebd-53150a534dd3.png)

And when it is functioning:

![image](https://user-images.githubusercontent.com/6308683/43003773-3fce49f0-8c4b-11e8-944c-a1ad5d3eda48.png)

A subtle color shade change serves as a nice indicator. Though feel free to choose whatever change you seem fit. 

The dimensions for both will be the same.

> Can you change the icon on the fly?

Yep, a [single method call](https://developer.chrome.com/extensions/browserAction#method-setIcon) allows me to do this in one go.

**Comment by iWrote** [comment]
![gknobgdisabled](https://user-images.githubusercontent.com/18333895/43043688-95edccd6-8db6-11e8-91e6-5ce4068c600b.png)
![gknobgdisabledprevw](https://user-images.githubusercontent.com/18333895/43043690-98f8fb4e-8db6-11e8-9238-2d697aa77818.png)

I tried doing something like [this](https://www.google.com/search?q=keyboard+broken+key&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiE45eGpLLcAhXFOI8KHe8UCNgQ_AUICigB&biw=1536&bih=727#imgrc=YMDsoiipizUu_M:) but i guess with such small res a simple greyscale filter works best.
Attached icon:  [gkNoBgDisabled.zip](https://github.com/GaurangTandon/ProKeys/files/2216819/gkNoBgDisabled.zip)
