### ISSUE TITLE
Shift from png icons to svg(or a font like fontawesome)

### ISSUE THREAD

**Issue by ammarbinfaisal** [GaurangTandon/ProKeys#219]
png icons look a bit blurred and pixelated(particularly the delete snippets, bulk action, sort, edit icons).
All of the icons(with slight changes but for same purpose) are available on fontawesome so you can try that.

**Comment by GaurangTandon** [comment]
Hey, I had actually sourced all of my icons from FontAwesome itself.  However, instead of downloading the icons, I just took their screenshot :P That is why they may be blurred. 

Now I can also see that FA5 has been released, so that's probably another good reason to upgrade my icon set :)

**Comment by GaurangTandon** [comment]
FA is supplying a large SVG file only. Any idea how to download just a small jpeg file only? (I'm not using `<i class="fa-"></i>` because I can't afford all of the icons in the library)

**Comment by ammarbinfaisal** [comment]
It is simple.<br/>You just have to copy svg element from the webpage and place it in your html file. then fix the width/height with css to what you want it to be.<br/>
Look at the screenshot below.
![fa](https://user-images.githubusercontent.com/30975614/44309570-7c6b1c00-a3e6-11e8-9e14-885de0d32ae1.png)

**Comment by ammarbinfaisal** [comment]
You can save the copied svg to another svg file and use them in the html doc with the img tag and that I think wil be better

**Comment by GaurangTandon** [comment]
Thanks for that Ammar! This should be part of the next build. If you're interested, consider submitting a PR as well ;)

**Comment by ammarbinfaisal** [comment]
I am almost done.
Just tell me that should I replace the social share icons with the svg ones as well?

**Comment by GaurangTandon** [comment]
Yeah, if possible, please do! :)
