### ISSUE TITLE
Feature Request (?) - Allow html elements in rich text entry

### ISSUE THREAD

**Issue by lee-tts** [GaurangTandon/ProKeys#221]
Specifically, I am hoping to be able to use a horizontal rule `<hr>` tag in the snippet. So, for example, when I type hr and trigger the snippet, I will get a horizontal rule / line. Other html elements like this might also be desirable, but for now the one I really want to use is the `<hr>` element. Simply pasting one into the snippet's rich text area doesn't work at the present time. 

If it's already possible somehow, then this issue can be closed.

Much appreciated extension! Thanks,

Lee

**Comment by GaurangTandon** [comment]
Hey, sorry for the late response!

This is already possible in the latest ProKeys version. Simply go to the Textarea mode snippet editing, type something like:

```
abcd
<hr>
1234
```

and then execute it in some rich text webpage, like Gmail, and it will automatically insert a horizontal rule.

Hope that helps!
