### ISSUE TITLE
Improvement in export modal v3.1

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#23]
Instead of:

![image](https://cloud.githubusercontent.com/assets/6308683/16525754/812515ce-3fcb-11e6-98f3-037a3fd63f40.png)

we can put just 3 simple radio boxes under heading "Choose use of data":
1. Backup entire data 
2. Backup only snips
3. Print all snips

as, when you try to select, in the current version, "Entire data" followed by "to print...", you get the same data as you'd get if you select "Entire data" and then "to backup"

**Another solution (better)**

The combination of "Entire data" followed by "to print..." should give printable data including all properties in user settings.

**Comment by iWrote** [comment]
Why not just have 3 buttons then? 
Backup entire data
Backup snippets
Print snippets

Clicking them should begin the download.

p.s. why would a user want to print the snippets?

**Comment by GaurangTandon** [comment]
Oh yes, good idea!

> p.s. why would a user want to print the snippets?

I saw multiple user comments on another similar and popular text expander's page asking for this functionality, so.

**Comment by GaurangTandon** [comment]
Was very easy work.
