### ISSUE TITLE
Would be great to have the tab key as the hotkey function 

### ISSUE THREAD

**Issue by JawadS** [GaurangTandon/ProKeys#238]
Hi user! Please use this template to easily file your issue:

### Data
**Browser name:** - %YOUR_BROWSER_NAME%
**OS name:** - %YOUR_OS_NAME%
**Site** where ProKeys is functioning improperly - %site_url%
### **Description:**
**Steps to reproduce issue**
Doing the following in latest ProKeys version will cause the problem I'm writing about.

1. %step_1%

**Actual behavior**
The above steps result in: %describe%

I understand there's an option to have tab create 4 spaces, however I think it's much better off being used as the actual hotkey. 

**Expected behavior**
The following was supposed to happen/should have happened: %describe%

Set tab as the hotkey. 

-------

- [ ] - I have confirmed the issue occurs even after reinstall (and data backup) of ProKeys  
_(ignore if not applicable)_

**Comment by GaurangTandon** [comment]
Hi, sorry for my delayed activity on this. I have attempted a fix in https://github.com/GaurangTandon/ProKeys/commit/4d1c7b0532f324faf63ba8a8aa16e257e13cd646 however it has not yet yielded positive results. I'll update when I fix this finally. Thanks for your patience!
