### ISSUE TITLE
[Feature Request] Add Option to Disable Context Menu

### ISSUE THREAD

**Issue by alivefromupstairs** [GaurangTandon/ProKeys#239]
**Browser name:** - Chrome Version 71.0.3578.98 (Official Build) (64-bit)
**OS name:** - Windows 10/Linux Ubuntu
chrome's context menu is very inefficient and messy in and of itself. I personally try to keep in it things that I use on a regular basis. ProKeys' block site and snippets are rarely used from the context menu. can we have an option to disable it. Thanks. 
also, undo (ctrl+z) doesn't work good with the extension.

**Comment by GaurangTandon** [comment]
Thanks for the report @alivefromupstairs . Also sorry for my delayed response, I was busy with other stuff. This feature has been added and will be part of the new release :D
