### ISSUE TITLE
Check compatibility for multiple sites

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#27]
EverNote web
SRM
Workflowy
"Possibility of supporting Salesforce Service Cloud? 

It doesn't work as far as I know based on Sales force hosting an iframe in an iframe, in another iframe. Any insight would be awesome! 
<br>Right now I am working around this by expanding in another window and copy/pasting the expansion. "

_excerpts from users of other similar apps_

**Comment by iWrote** [comment]
Can't the user still use snippets from the right-click context menu? Seems easier than copy-paste <<< defeats the entire purpose of the extension. Or does that not work either?

(Assuming you've pasted a user complaint here. The context is unclear.)

**Comment by GaurangTandon** [comment]
Oops I forgot to edit out that copy-paste part. Though as I said before, these are "excerpts from users of other similar apps".

**Comment by GaurangTandon** [comment]
The following - mathomania, snippet expansion (letter/brb) with/without placeholders, using ctx menu/hotkeys, auto-inserts, tab key spaces, no console errors due to prokeys' file - reported to be correctly working on:

1. Evernote web - 100% correct
