### ISSUE TITLE
Parenthesis auto-insert mangles emoticon `:(`

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#28]
Press a colon and then pressing `(` auto inserts a `)` which makes the text `:()` instead of expected `:(`.

**Solution:**

Detect a colon press and prevent _just_ the parenthesis auto-insert right after it if `(` i s pressed. @iWrote Any other suggestions?

**Comment by iWrote** [comment]
The solution is ideal. Conventional punctuation never puts parens after colon. In fact, it broke google search :open_mouth:  

https://www.google.co.in/search?q=%3A(&oq=%3A(&aqs=chrome.0.69i59l2.727j0j7&sourceid=chrome&ie=UTF-8#q=search+:(*)

But that seems to work for other combinations of punctuation as well, nvm...

**Comment by GaurangTandon** [comment]
> But that seems to work for other combinations of punctuation as well, nvm...

I don't exactly get what you mean. You suggest I don't implement the suggested solution?

**Comment by iWrote** [comment]
Sorry, sorry, no. I was talking about the link-joke-thing. 

Implement the solution.

**Comment by GaurangTandon** [comment]
closed via #197
