### ISSUE TITLE
Possible fix for some React controlled input elements

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#287]
Here's a React based editor: https://codesandbox.io/s/vigorous-elion-ddxq3

As you can see if you expand brb or use `[]` in the editor, it does not catch a state update. This results in a lot of trouble for users.
The fix button emits a simple `input` event on the textarea which helps update the internal state.

Solution is to emit this event after every programmatic text insertion.

These things need to work as expected, at least on whatsapp web:

1. snippet insertion (hotkey/ctx menu)
2. Mathomania
3. auto-inserts

**Comment by GaurangTandon** [comment]
Also must verify #200 tests now that we have rewritten auto insert functionality.

**Comment by GaurangTandon** [comment]
All tests passed. Good to merge.

**Comment by ammarbinfaisal** [comment]
Hey, this is great!
I tried a lot do something similar once -- bulk post comments on instagram just to annoy someone :p
tried dispatching so many different kinds of event but they didn't work. I guess this was the only event which i didnt try.

**Comment by GaurangTandon** [comment]
@ammarbinfaisal yep you're right :) This is really one of those hidden mysteries in Web APIs. I've too struggled with it for long ([issue](https://github.com/GaurangTandon/ProKeys/issues/106)), even tried `execCommand`, but finally discovered this magical on input event :)

Though I can tell you this doesn't work everywhere. For example, on facebook this collapses the messenger chatbox :O
