### ISSUE TITLE
User on-boarding issues in ProKeys

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#29]
I read this guide and was pretty satisfied with what onboarding ProKeys is offering - https://medium.com/@harrybr/beyond-onboarding-ramping-up-your-users-from-novice-to-expert-689aa941e2e1#.bktf39bmk (it's for iOS but still majorly applicable to ProKeys)

But maybe I missed a few points so @iWrote could you please read it and just make sure ProKeys follows all guidelines (where applicable)

**Comment by iWrote** [comment]
I'll get back to you once i'm through it.

**Comment by iWrote** [comment]
**Abandonment antipattern**
While Prokeys does handle this reasonably well, 
1. I'll prepare a fresh set of preloaded snippets. Not fresh, I mean revised.
2. Send a pull request with an improved help page.

**FrontLoading**
Hardly relevant, we don't have a compulsory tutorial, and the promo video does a decent job of introducing Prokeys. The learning curve is gentle.
No action needed.

**Zone of Proximal Development** & **B=MAT**
We're probably in it. Vague thingamabob. 

The stuff below that doesn't strictly seem to apply to prokeys. And I haven't gone through it properly yet.

**Comment by GaurangTandon** [comment]
Oh great! Thanks! Just remember to NOT use the options.html present on github, I have a local upto-date version that I'll mail you when you need it.

**Comment by iWrote** [comment]
Okay. So editing it on my fork won't work?

**Comment by GaurangTandon** [comment]
yes, it won't work because I made local changes to that file which neither
your nor mine fork will have, because those changes are only on my pc.

**Comment by GaurangTandon** [comment]
Alternatively, I just created a new branch 'v310-update' with my latest changes. You can directly download options.html from [there](https://github.com/GaurangTandon/ProKeys/tree/GaurangTandon-v310-update).

**Comment by iWrote** [comment]
Unlist the 2014-15 promotional videos. They show up on a google search.
https://www.youtube.com/watch?v=0rpRpAxp_x4
https://www.youtube.com/watch?v=AgzlqP62QEs
(I've decided typing "No offense" in such situations is not necessary anymore.)

**Comment by iWrote** [comment]
Should we get someone to leave a review mentioning ProKeys on PopChrom's webstore page? Will that be too wrong?

**Comment by iWrote** [comment]
Question: Is the Opera version still alive?

**Comment by GaurangTandon** [comment]
> Unlist the 2014-15 promotional videos. 

Good point. Done.

> Should we get someone to leave a review mentioning ProKeys on PopChrom's webstore page?

Good idea! :) I think the v3.1.0 update might just be the right time. We can then ask Richard Myers to leave a review on Popchrom's page telling how bad it is. (There are still a few bugs in the current public version of ProKeys, so we ought to fix them before talking about others' bugs :P)

**Comment by GaurangTandon** [comment]
@iWrote #42 and #149 are subsets of this issue. We have one additional issue here: Zone of Proximal Development & B=MAT. Do you wish to work on this thing (and what exactly is its relation to prokeys) or do you wanna close the issue?

PS: I deleted random off-topic/obsolete comments above.

**Comment by iWrote** [comment]
Eh, vague discussion. Closing.

**Comment by GaurangTandon** [comment]
@iWrote So, "Zone of Proximal Development & B=MAT." isn't applicable to our app?
