### ISSUE TITLE
Add snippet macro to insert current browser URL

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#34]
`[[%(url1)]]` should produce `github.com/GaurangTandon`.
`[[%(url3)]]` should produce `github.com/GaurangTandon/ProKeys/issues`.
`[[%(url03)]]` should produce `www.github.com/GaurangTandon/ProKeys/issues`.
`[[%(url003)]]` should produce `http://www.github.com/GaurangTandon/ProKeys/issues`.

_(when used on this page)_

Any ideas for a better syntax, @iWrote ?

**Comment by iWrote** [comment]
I think the syntax should be consistent with date/time macros. So this is good. 
Maybe `[[%u(keyword)]]`
The u outside parens is more consistent. Easily relatable to other macros.

Keywords could be better though.

**Comment by GaurangTandon** [comment]
Yes, you're right. New syntax:

`[[%u(1)]]` should produce `github.com/GaurangTandon`
`[[%u(3)]]` should produce `github.com/GaurangTandon/ProKeys/issues`
`[[%u(w3)]]` should produce `www.github.com/GaurangTandon/ProKeys/issues`
`[[%u(pw3)]]` should produce `http://www.github.com/GaurangTandon/ProKeys/issues`
`[[%u(p3)]]` should produce `http://github.com/GaurangTandon/ProKeys/issues`

Here, the positive numeral refers to depth of `/` file to take out.
A `w` prefix means we have to prefix `www` to the url.
A `p` prefix means we have to prefix `http://www`  to the url.
`p` and `w` order doesn't matter and uppercase does not matter either. So, this should also work:

`[[%u(WP3)]]` should produce `http://www.github.com/GaurangTandon/ProKeys/issues`

*(all the above samples work when used on this page)*

What do you think now? @iWrote

**Comment by GaurangTandon** [comment]
But if the user wants to obtain just the second part of the path of the URL? (say `ProKeys` in the above case), what syntax do we use?

**Proposal:** 

1. `[[%u{p}]]` gets just the protocol (`https`).
2. `[[%u{3}]]` gets just the 3rd part of the url (`issues`)
