### ISSUE TITLE
Add privacy page

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#38]
With this text:

"
I enlist here the reasons (the bold headers are hyperlinks to the Chrome API docs which you can see; Opera uses the same API as well):
1. **storage** - to store the snippets and user settings
2. **notifications** - to display notifications on install and update
3. **tabs** - to inject the content script into the webpages on first install (helps ProKeys to work without page reload)
4. **<all_urls>** - is required to make sure ProKeys work on all websites (and access the text box where you type text)

As you see, no external data is collected and sent to any external servers. You are free to check out all the code on GitHub as well. It's mainly for the Chrome version, but the code is 99% same. Additionally, I may inform you that whenever any developer uploads/updates an addon, it is duly checked by an Opera moderator to make sure it meets all its rules, one of which says "It must not send private data to an external store, for example through XHR". Read all the rules here."

_(refers to Opera but can modify for Chrome)_

**Comment by GaurangTandon** [comment]
I'm going to add this in the v3.1.0 version. @iWrote is the text ok?

**Comment by iWrote** [comment]
4. - is reqd . . wait what? what is 4. - ?

Remove the mid-text smiley.

**Comment by GaurangTandon** [comment]
I removed the smiley but the 4th point is for `<all_urls>`. Are you seeing anything else? (or maybe gmail didn't render it properly?)

**Comment by iWrote** [comment]
https://www.diffchecker.com/h57bNV8w

I enlist here the reasons **for what??** (bold text links to Chrome API docs, which is shared by Opera.):

1. storage - to store the snippets and user settings
notifications - to display notifications on install and update
2. tabs - to inject the content script into the webpages on first install (helps ProKeys to work without page reload)
3. <all_urls> - is required to make sure ProKeys work on all websites (and access the text box where you type text)

No external data is collected and sent to external servers. You can check out all the code on GitHub as well. It's mainly for the Chrome version, but the code is 99% same. Whenever any developer uploads or updates an addon, it is duly checked by an Opera moderator to make sure it meets all its rules, one of which says "It must not send private data to an external store, for example through XHR". Read all the rules here.

**Comment by GaurangTandon** [comment]
I realised that people should have access to reasons for permissions **before** installing the extension. So, I've created a github file instead. [Here it is](https://github.com/GaurangTandon/ProKeys/blob/master/PERMISSIONS_EXPLAINED.md). 

@iWrote Make proper grammar changes directly in it. And then give your thumbs up.

PS: I'll add the Opera version in it later.

**Comment by GaurangTandon** [comment]
Added Opera version. Awaiting thumbs up.

**Comment by iWrote** [comment]
thumb's up
taste the thunder
