### ISSUE TITLE
Revising Help & FAQ

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#42]
#29 in not closable. Help page is better off as a separate issue.

**Comment by iWrote** [comment]
@GaurangTandon  I seem to have write permissions in the collaboration folder of the v3.1.0 branch. Shall I just make direct changes there? (While being very, very careful not to leave typos around in that jungle.)

**Comment by GaurangTandon** [comment]
@iWrote You should. Typos and other things aren't a big folder. Git is a Version Control System. That's why we're using it, to keep track of (and rollback to if needed) past versions as well.

**Comment by iWrote** [comment]
Typos aren't a big folder? Folder?

**Comment by GaurangTandon** [comment]
I had edited it in 5 seconds of posting to make "folder" to "problem". Seems like email notifs are sent too instantly.

**Comment by GaurangTandon** [comment]
Deferred to a farther release. 

**Additional suggestion:**

We get many many requests about how to use the date time stamp, even though it is very thoroughly detailed in the help section. It must be that the language is unclear/confusing. When you start revising help&faq, make it a priority to first review the date/time stamp section in the help page.

**Comment by GaurangTandon** [comment]
@iWrote Do you ever wish to do this?

**Comment by iWrote** [comment]
Merged with #149
