### ISSUE TITLE
Conflicts with Grammarly

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#43]
Issue created in reference to a user complaint on the Chrome Webstore.

[Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) glitches while running in parallel with ProKeys. Sometimes spellcheck just stops working while testing in Gmail.

I'll ask the user for more details.

Edit: Actually a fresh install of ProKeys after installing Grammarly, and then reloading the page, seems to get rid of all issues. At least on Gmail.

**Comment by GaurangTandon** [comment]
I am sorry for the user (he's a long-time ProKeys fan), but, this is a 3.2.0 milestone.

**Comment by GaurangTandon** [comment]
Few updates, everything works except mathomania
There's a few console errors. Would look into this.

**Comment by GaurangTandon** [comment]
Hmm, so ProKeys raises no errors while Grammarly keeps raising CRLErrors in multiples of nine...very odd! Closing this issue as there isn't much I can do for this now.
