### ISSUE TITLE
Enclose highlighted text in punctuation

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#56]
![captur2e](https://cloud.githubusercontent.com/assets/18333895/21803703/443771c0-d751-11e6-9125-7720ff909bc8.PNG)

Similar behaviour for [ { ( will be appreciated.

**Comment by GaurangTandon** [comment]
Hmm, interesting. I actually wanted something like this but never got the `Shift+"` idea.

**Comment by GaurangTandon** [comment]
hey how do you account for the edge case where user wishes to type `[]` and presses Shift+`{` (both symbols have the same key). How do I know if the user wishes to type `[` or `{`??

**Comment by iWrote** [comment]
Alt+Space then?

**Comment by GaurangTandon** [comment]
_`Alt`+`Space`+(symbol user wishes to type - additional `Shift` in case of `{`)_ - isn't it too long a combo? :(

**Comment by iWrote** [comment]
Can you detect double taps? I never suggested this because I didn't know if it was possible. Then I saw the issue about timers.

Select text - - > double tap - - > enclosed text.

http://stackoverflow.com/questions/6420826/double-tap-interval-time-standard



**Written assuming hitting space is necessary in every ProKeys function.** (Because I didn't include space in my original proposition. I never realised that space MUST be a part of every feature.)
(Also, I deleted the knee-jerk alt+space response above.)

**Comment by GaurangTandon** [comment]
> Can you detect double taps?
Yes, I can. But, am hoping for a better option.
> Written assuming hitting space is necessary in every ProKeys function. 
Nope. it's not. What other suggestions do you have without this assumption?

**Comment by iWrote** [comment]
imho double tap will be the absolute ideal solution. Why're you sceptical about it? 

And if Space isn't necessary, then `Alt+ (Shift) + char`  isn't that long for a functionality you won't be using all the time

**Comment by GaurangTandon** [comment]
@iWrote I just hope Alt+char isn't a reserved key comb sort of thing.

**Comment by GaurangTandon** [comment]
I was wondering, after having used different Coding IDEs, that the functioning you suggest should instead be the _default behavior._ What do you think?

**Comment by iWrote** [comment]
Yeah. Let the users have an option to disable it, though. 

I'm usually annoyed when the text is replaced by a stupid ` " `.

But a lot of times I also find myself replacing text with dialogue/enquotedStuff.

**Comment by GaurangTandon** [comment]
closed via #200. Instead of unnecessarily messing with the keycodes, this is now a boolean setting under Settings page.
