### ISSUE TITLE
Auto-Insert problem in case of double quotes

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#7]
When I press `(` and then `)`, the second brace is overwritten properly so it enhances user experience.

But, the same does not happen in case of double quotes. Pressing double quotes twice gives four quotes.

**Comment by iWrote** [comment]
IF       double quotes are hugging cursor
THEN don't autocomplete
Why isn't this implemented like the double quotes?

**Comment by GaurangTandon** [comment]
You mean to say when such a posn happens: `"|"`, then I shouldn't auto-complete. You're right but this isn't the way how the user works. User will insert the double quotes and get this posn - `"|"` - and then e'll type some good deal of text to get this `"Hello Person|"`. So, soln is to check if there's no single quote that follows the cursor when the double quote key is pressed.

**Comment by GaurangTandon** [comment]
Technically this should work following from the code for other auto-insert characters. Don't understand what the problem is :/
