### ISSUE TITLE
Test sync storage on two laptops - using chunked data settings

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#74]
to make sure it's working properly, before pushing v3.1.0 update.

**Comment by iWrote** [comment]
send me the packed folder if you need me to do it across diff os

**Comment by GaurangTandon** [comment]
Perfect, @iWrote :) Let me just clear up few things first.

**Comment by GaurangTandon** [comment]
Hey, this is the last issue standing before us. I'll send you a link to an unlisted crx extension+list of testing guidelines today eve or tomo afternoon to test the sync storage.

**Remember:** **We are NOT taking any careless risks with user data** that's the most precious thing. Even if the testing means delaying the long-awaited update by 1 or 2 days, we must do that.

**Comment by GaurangTandon** [comment]
I have postponed chunked data storage for v3.2 So, did a normal manual checkup and everything looks good!
