### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by unlocomqx** [GaurangTandon/ProKeys#8]
**Browser name:** Chrome
**OS name:** - Win7
**Description:** I got a JS error in chrome console

```
Uncaught TypeError: Cannot read property 'substring' of undefined
snippet_classes.js:formatted:154
```

Line: 
`return t.timestamp = "number" == typeof e.timestamp ? e.timestamp : Date.parse(e.timestamp.substring(11)),`

I can't use the extension due to this error
This happens in the Options page as well as Regular webpages

Probable cause: My saved snippets don't have all the same structure, some contain the keys [body, name, timestamp] while others only have [body, name] or timestamp is null
`{"name":"brg","body":"best regards","timestamp":null}`

Please fix it, thank you

**Comment by GaurangTandon** [comment]
I am extremely sorry for whatever has happened in v3.0.0 and I have tried to resolve this at the earliest. I had worked hard on this update but didn't know it would break the data. Thank you for your patience. It is highly valued.

I have uploaded a new version with a possible bug fix. It should be up on [this page](https://chrome.google.com/webstore/detail/prokeys/ekfnbpgmmeahnnlpjibofkobpdkifapn/support) within 60mins. You can go to chrome://extensions in Chrome and click "Update extensions now" button in the top to update ProKeys immediately.

Thank you for your support once again. It is deeply appreciated! :)

P.S. Additional thank you for nailing down the problem to the exact pin-point cause! ;)

**Comment by unlocomqx** [comment]
Don't worry bro, I'm a dev myself and these things happen, I will check your fix asap

Thanks you

**Comment by unlocomqx** [comment]
It's fixed, great job mate :+1:
