### ISSUE TITLE
Compile list of similar extensions

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#87]
I need to be aware of all of them too.

**Comment by GaurangTandon** [comment]
Some are [here](http://alternativeto.net/software/prokeys/) and the rest are Popchrom (abandoned) and Text Blaze (new project; growing fast; prodigal son).

Rest are too much macro keys oriented (iMacros).

**Comment by GaurangTandon** [comment]
Is there anything else you're looking for? (If not, please close the issue :P)
