### ISSUE TITLE
Prokeys not working after update

### ISSUE THREAD

**Issue by cjm39** [GaurangTandon/ProKeys#9]
**Browser name:** - CHROME
**OS name:** - WIN_7
**Site** where ProKeys is functioning improperly - ALL
**Description:** Prokeys isn't working at all. The "options" page 
![capture](https://cloud.githubusercontent.com/assets/19611526/15612598/af755f60-23ec-11e6-85d8-decb7dd3b111.JPG)
is blank except for the link to "Prokeys" in the chrome store (which does work) and the links "Snippets", "Settings", "Help", "About" (which do nothing when clicked).
Snippets do not work on any website.

**Comment by GaurangTandon** [comment]
I am extremely sorry for whatever has happened in v3.0.0 and I have tried to resolve this at the earliest. I had worked hard on this update but didn't know it would break the data. Thank you for your patience. It is highly valued.

I have uploaded a new version with a possible bug fix. It should be up on [this page](https://chrome.google.com/webstore/detail/prokeys/ekfnbpgmmeahnnlpjibofkobpdkifapn/support) within 60mins. You can go to chrome://extensions in Chrome and click "Update extensions now" button in the top to update ProKeys immediately.

Thank you for your support once again. It is deeply appreciated! :)

**Comment by cjm39** [comment]
Looks like it's fixed.
Thanks so much!
Love the app!

**Comment by GaurangTandon** [comment]
That' awesome! :D Thanks!
