### ISSUE TITLE
ProKeys should auto-import past data on reinstall

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#93]
Just today I reinstalled StayFocusd, silently grim that I would have to re-enter all those settings. But magically, StayFocusd imported all those settings from somewhere (localStorage obviously :D). 

**WORK:** Implement something like this for ProKeys. You already have Past Data Versions - just make sure that they're checked for once on install.

**Comment by QuantumInformation** [comment]
Yeah this is really annoying

**Comment by GaurangTandon** [comment]
Took one step towards this with #255

**Comment by GaurangTandon** [comment]
This also presents a security risk, for example, if the user uses a company pc and leaves their job uninstalling ProKeys, thinking that their data is gone now. However, it isn't and a new employee could get access the old data.

How to make this more apparent though?

**Comment by GaurangTandon** [comment]
Actually, I also made an MCVE for this, but it seems neither chrome.storage nor localStorage persist across extension reinstalls. 
(I also verified this isn't an issue with unpacakaged chrome extensions as they retain the same id.)

So, for now, there is no good way to achieve this.

**Comment by QuantumInformation** [comment]
user accounts would be nice

**Comment by GaurangTandon** [comment]
Hey @QuantumInformation , you're right they would be nice. However, we already offer sync storage, so user can use that if they wish to. From what I can understand [from here](https://stackoverflow.com/questions/23210499/chrome-storage-local-persistence), such storage should persist across reinstalls.
