### ISSUE TITLE
Add Sync troubleshooting to Help page

### ISSUE THREAD

**Issue by GaurangTandon** [GaurangTandon/ProKeys#98]
"
I know you've tried this, but listing leads to inspiration -
1. Maybe she has a nobody-mode-chrome shortcut on her desktop which she conveniently clicks and then complains about sync.
2. Or she set up sync in the wrong order?
3. Or she expects it to sync across different google accounts? (Assuming that can't happen.)
4. Or maybe she's confusing similar accounts. I once had Ubi support mail me my login mail after a 4 day long authentication process. I realised I was logging in through the wrong one.

If it helps, here's how I checked sync-
1.Fresh prokeys install, snippet created, sync-store-first time clicked
2.<switched to different pc>
3.started chrome, enabled Varun mode (I'm sorry, I just like calling it that), 4.prokeys fresh install, sync-already-set-up button

5.It worked.
"

courtesy @iWrote

**Comment by GaurangTandon** [comment]
Does this look good @iWrote (thumbs up so I may commit code and close the issue)

> 
> 1. Make sure that you're signed into Chrome. The tab on the top-right of the Chrome window should not read "Person".
> 2. Make sure that you click the two sync buttons in the right order - the first button is used when you're setting up sync for the first time, the second button is used when you already have sync set up on another PC.
> 3. Also, note that any particular data can be synced across one Google account only, so for both your Chrome browsers must be signed in with the same Google account.
> 4. In case you use multiple email accounts, make sure you're not confusing the ones which you use to sign-in to Chrome.
> 5. If still nothing work, contact us at prokeys.feedback@gmail.com

**Comment by iWrote** [comment]
> 1. Make sure that you're signed into Chrome. The tab on the upper-right corner of the title bar should not read "Guest".
> 2. Data can be synced across one Google account only. Both your Chrome browsers must be signed in with the same Google account. 
> 3. Click the two sync buttons in the right order - use the first button when you're setting up sync for the first time; the second button when you already have sync set up on another PC.
>  4. In case you use multiple email accounts, make sure you're not confusing the ones which you use to sign-in to Chrome.
>  5. If it still doesn't work, contact us at prokeys.feedback@gmail.com

Reordered points, minor edits - https://www.diffchecker.com/yMF8Bwb6

**Comment by GaurangTandon** [comment]
Perfect. Made the changes. Thanks! @iWrote
